
project_id = "imrmboyczebjlbnkgjns"

[functions.twilio-voice]
verify_jwt = false

[functions.twilio-token]
verify_jwt = false

[functions.thoughtly-contacts]
verify_jwt = false

[functions.retrieve-leads]
verify_jwt = false

[functions.store-leads]
verify_jwt = false

[functions.thoughtly-get-contacts]
verify_jwt = false

[functions.thoughtly-call-contacts]
verify_jwt = false

[functions.generate-sms-csv]
verify_jwt = false

[functions.send-sms-csv-email]
verify_jwt = false
