
# This is an example to get you started
# A Deno project for Supabase Edge Functions
project_id = "imrmboyczebjlbnkgjns"

[build]
include = ["src/pages/**", "supabase/functions/**"]
exclude = ["**/node_modules"]

[functions.twilio-token]
verify_jwt = false

[functions.twilio-voice]
verify_jwt = false

[functions.sms-webhook-receiver]
verify_jwt = false

[functions.sms-test-webhook]
verify_jwt = false

[functions.sms-test-gateway-webhook]
verify_jwt = false

[functions.sms-webhook-test]
verify_jwt = false

[functions.sms-send-single]
verify_jwt = false

