
project_id = "imrmboyczebjlbnkgjns"

[functions.twilio-voice]
verify_jwt = false

[functions.twilio-token]
verify_jwt = false

[functions.thoughtly-contacts]
verify_jwt = false

[functions.retrieve-leads]
verify_jwt = false
