
project_id = "imrmboyczebjlbnkgjns"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true
bucket_size = 100

[auth]
enabled = true
site_url = "http://localhost:3000"

[analytics]
enabled = false

[experimental]
multisite = false

# CRITICAL: Explicitly disable JWT verification for ALL Twilio-related functions
# Ensure all invoker roles are added for maximum compatibility
[functions]
[functions.store-leads]
verify_jwt = false
invoker_roles = ["anon", "service_role", "authenticated", "postgres"]

[functions.twilio-voice]
verify_jwt = false
invoker_roles = ["anon", "service_role", "authenticated", "postgres"]

[functions.twilio-token]
verify_jwt = false
invoker_roles = ["anon", "service_role", "authenticated", "postgres"]

[functions.twilio-stream]
verify_jwt = false
invoker_roles = ["anon", "service_role", "authenticated", "postgres"]

[functions.generate-client-portal]
verify_jwt = false
invoker_roles = ["anon", "service_role", "authenticated", "postgres"]

# SMS Gateway API functions
[functions.sms-send-single]
verify_jwt = false
invoker_roles = ["anon", "service_role", "authenticated", "postgres"]

[functions.sms-send-multiple]
verify_jwt = false
invoker_roles = ["anon", "service_role", "authenticated", "postgres"]

[functions.sms-send-to-contacts]
verify_jwt = false
invoker_roles = ["anon", "service_role", "authenticated", "postgres"]

[functions.sms-retrieve-messages]
verify_jwt = false
invoker_roles = ["anon", "service_role", "authenticated", "postgres"]

[functions.sms-retrieve-messages-for-lead]
verify_jwt = false
invoker_roles = ["anon", "service_role", "authenticated", "postgres"]

[functions.sms-contact-management]
verify_jwt = false
invoker_roles = ["anon", "service_role", "authenticated", "postgres"]

[functions.sms-get-balance]
verify_jwt = false
invoker_roles = ["anon", "service_role", "authenticated", "postgres"]

[functions.sms-webhook-handler]
verify_jwt = false
invoker_roles = ["anon", "service_role", "authenticated", "postgres"]

# AI SMS Agent function
[functions.ai-sms-agent]
verify_jwt = false
invoker_roles = ["anon", "service_role", "authenticated", "postgres"]
