
project_id = "imrmboyczebjlbnkgjns"

[functions.save-pitch-deck]
verify_jwt = false

[functions.retrieve-pitch-deck]
verify_jwt = false

[functions.send-pitch-deck]
verify_jwt = false

[functions.send-gmail]
verify_jwt = false
