
# This file controls the configuration for your Supabase project.
project_id = "imrmboyczebjlbnkgjns"
app_settings.streaming.minimum_version = "1.23.0"

[functions."twilio-token"]
verify_jwt = false
