
# A string used to distinguish different Supabase projects on the same host. Defaults to the working
# directory name when running `supabase init`.
project_id = "SalesPro"
# The port to use for the API URL in the local dev environment. Defaults to 54321.
api_port = 54321

# Email testing
[email_testing]
# Email testing is disabled by default. This only applies to the local dev environment.
enabled = false

# The difference between the access token and refresh token is the time they expire.
[auth.jwt]
# By changing this value you will invalidate all tokens issued to users.
anon_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0"
service_role_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImV4cCI6MTk4MzgxMjk5Nn0.EGIM96RAZx35lJzdJsyH-qQwv8Hdp7fsn3W0YpN81IU"

[functions]
# The port to use for Edge functions in the local dev environment. Defaults to 54323.
port = 54323

# Verify JWT
# When set to true, JWT verification is enabled on all functions. Defaults to true.
# default_verify_jwt = true

# Configure individual Edge functions:
[functions.thoughtly-call-contacts]
verify_jwt = false

[functions.twilio-voice]
verify_jwt = false

[functions.twilio-stream]
verify_jwt = false
