
# project configuration in supabase/config.toml
project_id = "imrmboyczebjlbnkgjns"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[functions.sms-webhook-receiver]
verify_jwt = false

[functions.sms-webhook-handler]
verify_jwt = false

[functions.ai-sms-agent]
verify_jwt = false

[functions.conditions-update-sms]
verify_jwt = false

[functions.twilio-token]
verify_jwt = false

[functions.twilio-voice]
verify_jwt = false

