
project_id = "imrmboyczebjlbnkgjns"

[functions.sms-webhook-receiver]
verify_jwt = false # Make this endpoint publicly accessible for webhook calls

[functions.sms-test-webhook]
verify_jwt = false # Make this endpoint publicly accessible for testing

[functions.sms-send-single]
verify_jwt = true

[functions.sms-register-webhook]
verify_jwt = true
